### ISSUE TITLE
ConceitoBasicoPy_Exercicio010

### ISSUE THREAD

**Issue by LuciBustamante** [Daniela-ndv/ExerciciosPython_SquadMaryJackson#9]
#### Exercício

Faça um Programa que utilize 4 variáveis como preferir e no final print uma mensagem amigável utilizando as variáveis criadas. 
Exemplos de variáveis: nome, idade, lugar, profissão ....
Exemplo de retorno: Olá Maria, prazer te conhecer. Sou de São Paulo também e estou migrando de área. 
Lembrando que para o retorno vamos usar print com as variáveis criadas e este texto é somente um exemplo, utilizem a criatividade.

**Comment by daniela-ndv** [comment]
Close #9
